name: Fetch Cat Image and Detect Cat

on:
  push:  # Trigger the workflow on every commit

jobs:
  cat_image_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests opencv-python-headless

      - name: Fetch Cat Image
        env:
          CAT_API_KEY: ${{ secrets.cat_api_key }}
        run: |
          python cat_detector.py  # Replace with the actual name of your Python script

      - name: Detect Cat
        run: |
          python cat_detector.py  # Replace with the actual name of your Python script
